### ISSUE TITLE
session data not saving

### ISSUE THREAD

**Issue by geekyme** [ffissore/connect-orientdb#3]
Hi @ffissore 

please help. I am using your library to save sessions in orientdb.

A session record is created successfully. 

However, it does not update the store when i do this: 

<pre>
// user is a an object containing username, etc...
req.session.user = user;

</pre>

what should i do?

**Comment by ffissore** [comment]
Doesn't it update the store at all? Is it missing some data? (I do a `JSON.parse(JSON.stringify(session))` call to filter out anything that's not pure data)
Can you provide the output of `npm ls`?

**Comment by geekyme** [comment]
It only creates the Session document / record in OrientDB. And thereafter when i attempt to change the req.session object, by doing req.session.user = user, it does not save this newly added property ('user') into the database.

However, when i call req.session.destroy(), it successfully deleted the corresponding session record in OrientDB. I had tried manually calling req.session.save() to no avail.

here's npm ls. I use a lot of various packages.

<pre>
├── async@0.1.22
├─┬ bcrypt@0.7.5
│ └── bindings@1.0.0
├─┬ connect-orientdb@0.1.0
│ └── coffee-script@1.6.2
├── debug@0.7.2 extraneous
├─┬ everyauth@0.3.1 extraneous
│ ├─┬ connect@1.9.2
│ │ ├── formidable@1.0.13
│ │ ├── mime@1.2.9
│ │ └── qs@0.5.6
│ ├── debug@0.5.0
│ ├── node-swt@0.1.1
│ ├── node-wsfederation@0.1.1
│ ├── oauth@0.9.10
│ ├── openid@0.5.1
│ ├── request@2.9.203
│ └─┬ xml2js@0.2.6
│   └── sax@0.4.2
├─┬ express@3.2.0
│ ├── buffer-crc32@0.2.1
│ ├── commander@0.6.1
│ ├─┬ connect@2.7.6
│ │ ├── buffer-crc32@0.1.1
│ │ ├── bytes@0.2.0
│ │ ├── formidable@1.0.11
│ │ ├── pause@0.0.1
│ │ └── qs@0.5.1
│ ├── cookie@0.0.5
│ ├── cookie-signature@1.0.1
│ ├── debug@0.7.2
│ ├── fresh@0.1.0
│ ├── methods@0.0.1
│ ├── mkdirp@0.3.5
│ ├── range-parser@0.0.4
│ └─┬ send@0.1.0
│   └── mime@1.2.6
├── Faker@0.5.8 extraneous
├─┬ fb@0.6.2 extraneous
│ ├── crypto@0.0.3
│ └── request@2.9.203
├── geoip-native@0.0.8 extraneous
├─┬ glossary@0.1.1 extraneous
│ ├─┬ natural@0.1.21
│ │ ├── apparatus@0.0.7
│ │ ├── sylvester@0.0.21
│ │ └── underscore@1.4.4
│ ├── pos@0.1.2
│ └── underscore@1.1.7
├─┬ jade@0.29.0
│ ├── character-parser@1.0.0
│ ├── commander@0.6.1
│ ├── mkdirp@0.3.5
│ ├─┬ monocle@0.1.43
│ │ └─┬ readdirp@0.2.4
│ │   └─┬ minimatch@0.2.12
│ │     ├── lru-cache@2.3.0
│ │     └── sigmund@1.0.0
│ └─┬ transformers@1.8.3
│   └─┬ promise@2.0.0
│     └── is-promise@1.0.0
├─┬ mailchimp@0.9.5
│ ├── qs@0.5.6
│ └─┬ request@2.16.6
│   ├── aws-sign@0.2.0
│   ├── cookie-jar@0.2.0
│   ├── forever-agent@0.2.0
│   ├─┬ form-data@0.0.7
│   │ └─┬ combined-stream@0.0.4
│   │   └── delayed-stream@0.0.5
│   ├─┬ hawk@0.10.2
│   │ ├── boom@0.3.8
│   │ ├── cryptiles@0.1.3
│   │ ├── hoek@0.7.6
│   │ └── sntp@0.1.4
│   ├── json-stringify-safe@3.0.0
│   ├── mime@1.2.9
│   ├── node-uuid@1.4.0
│   ├── oauth-sign@0.2.0
│   └── tunnel-agent@0.2.0
├── moment@2.0.0
├─┬ neo4j@0.2.20
│ ├── coffee-script@1.3.3
│ ├── http-status@0.1.1
│ ├── request@2.9.203
│ └── streamline@0.4.7
├─┬ node-minify@0.6.1
│ ├─┬ uglify-js@2.2.5
│ │ ├─┬ optimist@0.3.7
│ │ │ └── wordwrap@0.0.2
│ │ └─┬ source-map@0.1.22
│ │   └── amdefine@0.0.4
│ └─┬ uglify-js2@2.1.11
│   ├─┬ optimist@0.3.7
│   │ └── wordwrap@0.0.2
│   └─┬ source-map@0.1.22
│     └── amdefine@0.0.4
├── node-uuid@1.4.0
├─┬ nodemailer@0.3.44
│ ├─┬ mailcomposer@0.1.31
│ │ ├── mime@1.2.9
│ │ └─┬ mimelib@0.2.12
│ │   ├── addressparser@0.1.3
│ │   └─┬ encoding@0.1.6
│ │     └── iconv-lite@0.2.7
│ ├─┬ optimist@0.4.0
│ │ └── wordwrap@0.0.2
│ └─┬ simplesmtp@0.2.4
│   ├── rai@0.1.7
│   └── xoauth2@0.1.7
├─┬ orientdb@0.9.8
│ └── lodash@1.2.1
├── session.socket.io@0.1.6
├─┬ socket.io@0.9.14
│ ├── base64id@0.1.0
│ ├── policyfile@0.0.4
│ ├── redis@0.7.3
│ └─┬ socket.io-client@0.9.11
│   ├─┬ active-x-obfuscator@0.0.1
│   │ └── zeparser@0.0.5
│   ├── uglify-js@1.2.5
│   ├─┬ ws@0.4.25
│   │ ├── commander@0.6.1
│   │ ├── options@0.0.3
│   │ └── tinycolor@0.0.1
│   └── xmlhttprequest@1.4.2
├─┬ stylus@0.32.1
│ ├── cssom@0.2.5
│ ├── debug@0.7.2
│ └── mkdirp@0.3.5
└── validator@0.4.28
</pre>

**Comment by ffissore** [comment]
I'll try to debug it. Any other info/code to reproduce it will be helpful

**Comment by geekyme** [comment]
Sure thanks a lot. Here's more code to show how I set up the configurations on app.js

<pre>
var express = require('express');
app = express();
var OrientDBStore = require('connect-orientdb')(express);
var settings = {
    server: {
        host: "localhost",
        port: 2424
    },
    db: {
        user_name: "admin",
        user_password: "admin"
    },
    database: "blog",
    class_name: "Session"
};
var sessionStore = new OrientDBStore(settings);
app.configure(function(){
  app.set('views', __dirname + '/views');
  app.use(express.favicon() || express.favicon(__dirname + '/public/img/favicon.ico'));
  app.set('view engine', 'jade');
  app.set('view options', { doctype : 'html', pretty : true });
  app.use(require('stylus').middleware({ src: __dirname + '/public' }));
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser('super secret'));
  app.use(express.session({
    secret:'super duper secret',
    cookie: {
      httpOnly: true,
      signed: true/
    },
    store: sessionStore
  }));  
  app.use(express.csrf());
  app.use(function(req, res, next){
    //for jade access to csrf token
    res.locals.token = req.session._csrf;
    next();
  });
  app.use(express.static(__dirname + '/public'));  
  app.use(app.router); 
});
</pre>

**Comment by geekyme** [comment]
here's my usage scenario of req.session.user = user

<pre>
User.get(response.id, function(err, user){
            if(err) return next(err)
            if(user){
                console.log('retrieving user');
                //user present so just use current user data. no creation required.
                req.session.user = user;
                return res.redirect('/');
            }else{
                console.log('creating user');
                //create the user if its not present in the DB
                User.create(response, function(err, user){
                    if(err) return next(err);
                    //user successfully created. Saving user to session.
                    req.session.user = user;
                    return res.redirect('/');
                })      
            }
        })
</pre>

**Comment by geekyme** [comment]
Ok I got a full repo up for you to clone and reproduce the issue. I basically used the node-orientDB blog tutorial and i added session store to it. 

https://github.com/geekyme/orient-tut

I've adjusted the code in app.js to accommodate session storage. 
I've also adjusted the code in index.js to test fire altering of the req.session object. 

Here is what i've noticed from my lines of code in index.js (line 10 to 27, exports.index & exports.new_post_form):

If i have no session cookie, and I landed on '/', my session data will be created and inserted into orientDB. Even the randomly generated 'name' field (req.session.name) will be saved in orientDB store. Subsequently after being assigned a session cookie, if I navigate to '/new_post', the new session information is not saved. (look at the code line ' req.session.posting = true ');

If I have no session cookie and landed on '/new_post', req.session.posting = true will be saved in OrientDB. However, when I navigate to '/' the name field does not save. 

Overall, it only saves when there is no session cookie. After getting the cookie it doesn't save already.

**Comment by ffissore** [comment]
Well, I'm a bit ashamed. The code on github is long since committed and is working fine BUT it wasn't published on npm. Thant said: update the connect-orientdb module (now version is 0.5.0) and have fun.

BTW, at a first glance I'd say the wrong behaviour is in orientdb, since the old code (version 0.1.0) was working fine. I've asked them to give a look at the issue mentioned above.

Close this issue if the code is working for you too.

**Comment by geekyme** [comment]
Hey i updated the connect-orientdb module already. 
Now something else cropped up.

Error: [{"class":"com.orientechnologies.orient.core.exception.OCommandExecutionE
xception","message":"Target index 'SESSION.SID' not found"}]

**Comment by geekyme** [comment]
Oh cool beans! Now its working. I went to drop the Session class in my orientDB and restarted the blog tutorial app. Thanks a lot @ffissore !!
