### ISSUE TITLE
Expired Session not deleted in OrientDB session store

### ISSUE THREAD

**Issue by geekyme** [ffissore/connect-orientdb#4]
Hello, 

So I wrote some code to make my session cookies expire in 10 seconds:

<pre>
var sessionStore = new OrientDBStore(settings);

app.use(express.session({
    secret: 'joob 1232bs',
    cookie: {
      httpOnly: true,
      signed: true,
      secure: true,
      maxAge: 10000
    },
    store: sessionStore,
    key: 'skudi'
  }));  
</pre>

When I checked the OrientDB store 10 seconds after I access my web site, I still see the expired session record in the database.

Is there some sort of auto cleaning of expired sessions?

**Comment by ffissore** [comment]
AFAIK, there's no automatic trigger that deletes expired sessions. It seems neither connect nor expressjs have such. It should be implemented as a background task in connect-orientdb but the query may take a lot to execute

**Comment by geekyme** [comment]
Probably auto clear all expired sessions  every hour?

Or when the cookie expires, send something to the backend to delete the session?

**Comment by ffissore** [comment]
uhmm, ok, I've seen like stores like connect-couch do, I'll add a "reap interval"

**Comment by geekyme** [comment]
sounds good. need to see it in action though. let me know when you've made changes to the repo.

thanks!

**Comment by ffissore** [comment]
I've started implementing automatic expired session cleanup. "inspired" by connect-couch, there's a new option "reap_interval", defaulting to 10 minutes. It needs further testing though

**Comment by geekyme** [comment]
hi i just tried it. doesn't seem to work. i had reinstalled connect-orientdb from this repository.

**Comment by ffissore** [comment]
maybe the problem is that the first reap is run 10 minutes after the app is started. Should I add one at startup?

**Comment by geekyme** [comment]
hmmm nope. this was how i tested it:
1) delete all session from orientdb
2) start my node app
3) navigate to the app in the browser
4) select \* from session in orientdb to see 1 session record
5) waited about 20 mins ++ to see if the record was deleted... it wasn't deleted.

**Comment by ffissore** [comment]
fixed and released connect-orientdb 1.3.1, currently running on presentz.org
can you confirm?

**Comment by ffissore** [comment]
also released 1.3.2 that uses a default reap_interval of 10 minutes if none is specified

**Comment by geekyme** [comment]
its working! i've tested both specifying reap_interval and not specifying it. Both works. 
There's, however, a minor issue that i'm not sure whether its got to do with connect-orientdb. Whenever req.session is changed by say.... doing something like this:

<pre>req.session.cart = {item_name: 'bob'}</pre>

the 'expires' field will immediately update to the time when req.session is last changed. Is that suppose to happen?

**Comment by ffissore** [comment]
Yes it is: session is considered expired after a given amount of **inactivity**. This implies that any **activity** (even just browsing the app) should postpone the expire date

**Comment by geekyme** [comment]
Ok. Then everything is working fine then. thanks ! :)
